### ISSUE TITLE
large conda env management

### ISSUE THREAD

**Issue by jmvera255** [CHTC/chtc-website-source#69]
Currently the conda guide contains a note to check size of packed conda env after conda pack, but I think it would be best to make this note bigger and more obvious in the guide or to just be able to draw more attention to it (already noticed one user who has overlooked this)

**Comment by lmichael107** [comment]
Maybe it should be an obligate step (checking, and then placing in squid if
needed), rather than a note?

Lauren

Lauren Michael - Research Computing Facilitator, Center for High Throughput
Computing <http://chtc.cs.wisc.edu/>, University of Wisconsin - Madison
Other Affiliations: Wisconsin Institute for Discovery
<http://wid.wisc.edu/people/lauren-michael/>; Open Science Grid
<https://opensciencegrid.org/>; CaRCC <https://carcc.org/>
lmichael@wisc.edu, tinyurl.com/LMichaelCalendar, Discovery 2262,
(608)316-4430

**Comment by JoshKarpel** [comment]
Since the conda env will almost surely be shared between jobs and will be at least 10's of MB, should we just always have them place it in squid?

**Comment by jmvera255** [comment]
but if it's bigger than 1GB it should go to staging

**Comment by ChristinaLK** [comment]
agree w @lmichael107 that we should add checking as one of the steps not just a note.
