### ISSUE TITLE
Globus Documentation

### ISSUE THREAD

**Issue by bbockelm** [CHTC/chtc-website-source#82]
We've been happily tinkering with Globus for about 6 months now.  Things have gone swimmingly -- we should have some minimal pointers on how to use it (and/or work with @JoshKarpel and Infra to come up with a punchlist before we do so).

At a minimum, we need to document (a) it exists, (b) the endpoint name (and point out that the directory structure allows copies to/from staging), and (c) link to the upstream Globus docs.  I don't feel compelled to spend a lot of time teaching people how to use the service -- I'm OK with assuming that people come knowing how to use Globus and just want to use our instance.

**Comment by JoshKarpel** [comment]
Potential blockers, in my mind...
- We've been thinking of the current Globus endpoint on `transfer2001` as a "test endpoint". I don't think there's any real difference between how it is set up now and how we want the final product to be set up, except maybe whether it's on `transfer2001` instead of `transfer2000`?
- The endpoint is owned by me, in terms of what the Globus website says. Someone from the Infra team needs to be an admin, and ideally it should be owned by some impersonal account.
- The endpoint name is `chtc-test`. This is trivial to change to something "real", but we need to decide on the name. Just `chtc`? `chtc-staging`?
- There are some Globus endpoints out there owned by `chtc@globusid.org`, like `chtc#testsubmit`. The existence of these might confuse people, and it's distressing that we don't seem to know who this is. We should figure this out.

**Comment by ChristinaLK** [comment]
* do we want multiple endpoints if we have multiple transfer servers? or can we only have one? 
* agree that endpoint should be owned by some chtc admin type account. 
* I like `chtc-staging` as a name, especially if it lives on the transfer server. If we eventually have these on submit nodes, I think the submit node should factor into the name.

**Comment by JoshKarpel** [comment]
> do we want multiple endpoints if we have multiple transfer servers? or can we only have one?

AFAIK, we can have as many as we'd like total (one per machine).

**Comment by bbockelm** [comment]
- While we can have many, I would prefer to start with one until we see the need for multiple.
- There already is a CHTC account at Globus ... but it might be effectively owned by former team members.  @aaronmoate ?  @tjslauson ?
- How about `chtc-htc`?  Is `chtc#htc` an option?  Note this has access to both `/projects` and `/staging`!

**Comment by aaronmoate** [comment]
Dakota Chambers - former student hourly - was working on globus a few years back.  The CHTC account may have been created by him.

**Comment by lmichael107** [comment]
And I think you know how to get a hold of him, right, @aaronmoate ? He's still on campus somewhere else?

**Comment by aaronmoate** [comment]
I'm not sure yet, it's been a couple years since I've spoken to him.  @bbockelm , where is the web interface that deals with the CHTC account?  Can we get it to spawn a password reset email?  Then I can contact Dakota and ask if he's received it - or, in a best case scenario, maybe it goes to chtc-admin@cs.wisc.edu.

**Comment by JoshKarpel** [comment]
@aaronmoate I believe it should be this page: https://www.globusid.org/login

**Comment by aaronmoate** [comment]
I've recovered control of the chtc@globusid.org account;  coordinate with me to receive the password.

**Comment by ChristinaLK** [comment]
wahoo! nice work @aaronmoate . :)

next steps... finalize a naming scheme for endpoints, @JoshKarpel to draft an initial guide??

**Comment by JoshKarpel** [comment]
Sounds good; I think we also need to decide whether to keep hosting the endpoint on `transfer2001` or to make a new one on `transfer2000`. Given that we would want to re-create the endpoint under the `chtc@globusid.org` account anyway, it seems like an opportune time to move it to a permanent home. @aaronmoate  @bbockelm opinions?

**Comment by aaronmoate** [comment]
No strong opinions.  transfer2000.chtc.wisc.edu is the primary transfer server (transfer.chtc.wisc.edu is a CNAME for it), but I don't consider that to be a strong reason to make it the globus endpoint.  Can we not have multiple endpoints?

**Comment by JoshKarpel** [comment]
We can have as many as we'd like. The name of the server will be transparent to users; I think my question is more about whether we want different services on different hosts, or whether we want to put all the transfer services on one host.

**Comment by ChristinaLK** [comment]
I like the idea of having the endpoint on the main transfer server, just so it's less of a hassle for us if someone wants to use it - we don't have to give them a specific account on a specific server.

**Comment by JoshKarpel** [comment]
That makes a lot of sense to me. @aaronmoate do you want Infra to own the endpoint (i.e., you do the setup), or should I do it and write down all the details on the wiki?

**Comment by aaronmoate** [comment]
I'd like to puppet it if that's what you're asking, or at least as much of it as possible.  Please open an htcondor-inf ticket, I'll likely assign this to Emile.
